<a href="https://colab.research.google.com/github/PaulToronto/TensorFlow-Deep-Dive---Course/blob/main/Module_2_Building_Machine_Learning_Models_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 2: Building Machine Learning Models with TensorFlow

## Imports

In [ ]:
import numpy as np

## 2.1 Introduction to NumPy

- NumPy provides bindings to high-peforming compiled languages
    - Much more peformant for numerical computing than general Python objects
- `.numpy` attached to some TensorFlow objects
- NumPy idioms are used when working with the shape of TF objects
- NumPy's basic object is teh **homogeneous multidimensional array**
    - homogeneous it terms of `.dtype` of the elements
    - https://numpy.org/doc/stable/user/basics.types.html
- Excellent book for a deeper coverage of NumPy:
    - https://learning.oreilly.com/library/view/python-data-science/9781098121211/

In [ ]:
x = np.array([0, 0, 0])
x.dtype, x.shape

(dtype('int64'), (3,))

In [ ]:
x

array([0, 0, 0])

In [ ]:
print(x)

[0 0 0]


In [ ]:
y = np.ones([1, 3])
y.dtype, y.shape

(dtype('float64'), (1, 3))

In [ ]:
y

array([[1., 1., 1.]])

In [ ]:
print(y)

[[1. 1. 1.]]


In [ ]:
x + y * 2

array([[2., 2., 2.]])

In [ ]:
# a pointer to a specific location in memory
x.data

In [ ]:
y.data

## 2.2 From Arrays to Tensors